services:
  bot:
    restart: unless-stopped
    volumes:
      - ./config.py:/app/config.py
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      JISHAKU_NO_UNDERSCORES: true
